export const images = {
    bulb: '../../../assets/bulb.svg',
    cam: '../../../assets/camera-icon.svg',
    cross: '../../../assets/cross-close.svg',
    exclamation: '../../../assets/exclamation-alert-warning.svg',
    close: '../../../assets/icons8-cross-16.png',
    i: '../../../assets/i_Icon.svg',
    reload: '../../../assets/reload.svg',
    upload_box: '../../../assets/upload_box.svg',
    upload_attachment_clip: '../../../assets/upload-attachment-clip.svg',
    verified: '../../../assets/verified_Icon.svg',
    warning: '../../../assets/warning.svg',
    linkedIn: '../../../assets/linkedIn.png',
    twitter: '../../../assets/twitter.png',
    instagram: '../../../assets/instagram.png',
    discord: '../../../assets/discord.png',
    logo: '../../../assets/logo.svg',
    g:'../../../assets/g_logo.png',
    weekend:'../../../assets/weekend_logo.png',
    profile_picture:'../../../assets/profile-picture.jpeg',
    profile_icon:"../../../assets/profile-icon.png",
    for_you:"../../../assets/for_you.png",
    calendar:"../../../assets/calendar_.png",
    chat:"../../../assets/chat.png",
    events:"../../../assets/event.png",
    home:"../../../assets/home.svg",
    profile1: ".././../assets/profile1.jpeg",
    heart: "../../../assets/Icon heart.png",
    send_icon: "../../../assets/Icon paper plane.png",
    concert: "../../../assets/concert.jpeg",
    foodfestival: "../../../assets/food-festival.jpeg",
    exhibition: "../../../assets/exhibition.jpeg",
    sports: "../../../assets/sports.jpeg",
    next: "../../../assets/right-arrow.png",
    back: "../../../assets/left-arrow.png",
    work: "../../../assets/work.png",
    Education: "../../../assets/exercise.png",
    Gender: "../../../assets/gender.png",
    Location: "../../../assets/location.png",
    Height: "../../../assets/height.png",
    Exercise: "../../../assets/exercise.png",
    plus: "../../../assets/plus.png"
}